Main code
toobrainless/NeuralNetwork pull request #1
Opened 2022-05-05 13:39 UTC by toobrainless

2022-05-05 13:42 UTC, toobrainless commented on hello.txt
> +hello world!
Тестим комменты

2022-05-06 19:01 UTC, DimaTrushin requested changes
Я часть кода, которая после моих комментариев должна измениться, не комментировал. В остальном постарался проитись по всему. И еще не смотрел аккуратно методы Net. Посмотрим как они поменяются после моих комментариев.

2022-05-06 19:01 UTC, DimaTrushin commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 20)
лучше делать REQUIRED, чтобы при несоответствии стандарту он не понижался, а кидалась ошибка сборки.

2022-05-06 19:01 UTC, DimaTrushin commented on ComputeBlock.cpp
> +}
Добавь в конце всех файлов новую строку. На это даже гит ругается. Очень плохо иметь код, который при клонировании выдает ворнинг.

2022-05-06 19:01 UTC, DimaTrushin commented on ComputeBlock.cpp
> +using Matrix = Eigen::MatrixXd;
Такое использование using-ов плохо по нескольким причинам:
1) Рассинхрон с тем, что у тебя идет в header-е. Если ты исправишь тип вектора или матрицы на другой (например с float коэффициентами), то у тебя внизу ниже определение
```cpp
Vector ComputeBlock::predict(const Vector& x)
```
будет использовать текущий Vector из cpp файла в возвращаемом значении, и потому компилятор решит, что это определение другой функции, а ту функцию из класса ты просто не определил и это ошибка линковки. Хер найдешь такую.
2) Другая проблема -- определения в cpp файле всегда должны быть внутри анонимного namespace иначе у тебя тоже могут быть ошибки линковки, так как у линкера единое пространство имен.

Как бы я решал эту проблему. Я бы не вводил тут юзинги а писал бы так
```cpp
ComputeBlock::Vector ComputeBlock::predict(const Vector& x)
```
второй вектор, так как идет внутри функции, которая идет после квалификатора ComputeBlock::, автоматом подтянется из класса.

Если же ты хочешь использовать тут юзинги, то надо сделать так
```cpp
namespace {
using Matrix = ComputeBlock::Matrix;
using Vector = ComputeBlock::Vector;
}
```

2022-05-06 19:01 UTC, DimaTrushin commented on ComputeBlock.h
> +  Vector evaluate(const Vector &x) { return A_ * x + b_; }
почему метод не константный?

2022-05-06 19:01 UTC, DimaTrushin commented on ComputeBlock.h
> +  Vector predict(const Vector &x);
Почему метод не константный?

2022-05-06 19:01 UTC, DimaTrushin commented on ComputeBlock.h
> +  const Matrix &grad_A();
Следующие три метода похоже должны быть приватными. Вычислительный блок не должен их предоставлять пользователю.

2022-05-06 19:01 UTC, DimaTrushin commented on ComputeBlock.h
> +  std::shared_ptr<ComputeBlock> next_ = nullptr;
Вот это жуткое зло. Максимально жуткое и максимально злое! Нахуя, а главное зачем? Если ты хочешь огранизовать блоки в Linked list, то
1) Тебе достаточно использовать обычные указатели и чистить самому память.
2) Тебе можно использовать обычный std::list и хранить блоки в нем.

Кроме того, использование std::list позволяетне париться о флагах is_begin_ и is_end_.

Запомни, shared_ptr хорош только тогда, когда ссылается на константный объект. Во всех остальных случаях -- ты будешь страдать. А чтобы не страдать, он должен быть частью имплементации некоторой библиотечной структуры. Ты сначала имплементишь эту структуру, тестишь, и потом на ее основе собираешь нужный тебе объект. Я бы сказал, что такой подход опять намекает, что надо все хранить в std::list и не париться.

2022-05-06 19:01 UTC, DimaTrushin commented on ComputeBlock.h
> +  friend class Net;
Зачем Net объявлен другом? У тебя что, недостаточно методов в интерфейсе для взаимодействия с вычислительными блоками? Тогда ты неправильно распределил ответственности между классами.

2022-05-06 19:01 UTC, DimaTrushin commented on LossFunction.h
> +  double evaluate(const Matrix &z, const Matrix &y);
Почему два метода с одинаковым названием? В чем разница? Почему нет имплементации в cpp файле?

2022-05-06 19:01 UTC, DimaTrushin commented on Net.h
> +  Net(CountType layers, TolerenceType tol, StepType step);
Неплохая версия конструктора, но я бы ожидал не количество слоев в конструкторе, а размеры каждого слоя. Как ты сейчас определяешь размеры слоев?

2022-05-06 19:01 UTC, DimaTrushin commented on Net.h
> +  std::shared_ptr<ComputeBlock> begin_;
От этих shared_ptr можно избавиться с помощью std::list и работать с блоками через итераторы.

2022-05-06 19:01 UTC, DimaTrushin commented on Net.h
> +  std::unique_ptr<LossFunction> loss_;
А нахрена лосс функцию хранить через shared_ptr?

2022-05-06 19:01 UTC, DimaTrushin commented on main.cpp
> +  MatrixXd m(3, 3);
Функция main должна быть максимально абстрактная. Например
```cpp
#include "Tests.h"

int main() {
  run_all_tests();
  return 0;
}
```
и уже все детали имплментируешь внутри функции, которая гоняет тесты.

2022-05-07 19:09 UTC, DimaTrushin requested changes
Я не уверен, что это хорошая идея делать сигнализацию межд ComputeBlock-ами. Лучше сделать 
```cpp
class Net {
Vector predict(const Vector& x) const {
  Vector arg = x;
  for(const auto& layer : Layers) {
    arg = layer.predict(arg);
  }
  return arg;
}
void train(const Matrix& x, const Matrix& y) {...}
std::list<ComputeBlocks> Layers_;
};
```
Так тебе не придется менеджерить память. А за передачу данных между слоями будет отвечать нейросеть. Аналогично, вместо кеширования в слоях, можно в методе train завести кеш переменные и значния в них будет складывать нейросеть при обучении. У тебя ComputeBlock станет сильно проще и не будет решать лишнии задачи, которыми он заниматься не должен.

2022-05-07 19:09 UTC, DimaTrushin commented on ComputeBlock.h
> +    explicit ComputeBlock(MatrixSizeType shape);
А чем тебя не устроила пара rows, columns?

2022-05-07 19:09 UTC, DimaTrushin commented on ComputeBlock.h
> +        return last_output_;
Так как ты возвращаешь значение локальной переменной класса, то может быть разумнее возвращать const Vector&, чтобы не делать лишнюю копию. Ты же все равно запоминаешь вычисленное значение и не пишешь распараллеливание.

2022-05-07 19:09 UTC, DimaTrushin commented on ComputeBlock.h
> +    ComputeBlock *next_ = nullptr;
Меня смущает наличие указателей на другие блоки. Ты патаешься сделать так, чтобы блоки знали друг про друга и видимо чтобы они сигналили друг другу о том, что надо сделать пересчет.  Такая схема возможна, но тут лучше соединять все через observer pattern, а не в тупую. Можно сделать проще, можно перенести ответственность за передачу информации между блоками на класс, который будет содержать блоки, то есть на нейросеть. То есть вместо того, чтобы сигнализировать друг другу, у тебя нейросеть заведет итератор и пройдется по всем слоям сначала вперед, а потом назад и методы нейросети будут передавать информацию от слоя к слою. Так будет проще. Кроме того, это избавит не только от указателей, но и от булевых флагов "последний" и "первый". Ибо про это надо будет знать нейросети, а она это установит из итератора.

2022-05-07 19:09 UTC, DimaTrushin commented on Net.h
> +    using LayersShapes = std::vector<MatrixSizeType>;
Плохая идея. Для задания сети со слоями 2, 3, 4, 5 тебе придется делать так
Net({{2, 3},{3,4 },{4, 5}}. А любое дублирование информации черевато ошибками. Лучше сделай конструктор, который принимает количество слоев, потом в виде initialier_list принимает размеры слоев, а потом уже остальные параметы. ЭТо избавит тебя от ненужных тебе MatrixSizeTypeи LayersShapes.

2022-05-07 19:09 UTC, DimaTrushin commented on ComputeBlock.h
> +    bool is_end_ = false;
Зачем тебе эти флаги?
Во-первых, end -- плохое название, обычно end -- это "следующий за последним", а он всегда nullptr.
Во-вторых, last ты можешь обнаружить по условию next == nullptr. Аналогично begin устанавливается по previous == nullptr.

2022-05-07 19:09 UTC, DimaTrushin commented on Net.cpp
>  }
новая строка

2022-05-07 19:09 UTC, DimaTrushin commented on Net.h
> +    LayersShapes layers_;
Зачем это еще тут хранить?

2022-05-07 19:09 UTC, DimaTrushin commented on Net.h
> +    using Matrix = Eigen::MatrixXd;
Я бы написал ComputeBlock::Matrix и аналогично про вектор.

2022-05-07 19:09 UTC, DimaTrushin commented on Net.h
> +    void feed(const Matrix &x, const Matrix &y);
Не уверен, что это хорошее название метода. Вот что он делает? Он обучает? Тогда почему не назвать train?

2022-05-07 19:09 UTC, DimaTrushin commented on Net.cpp
> +        end_->train(step_);
Я бы назвал train текущую функцию feed, а эту как-нибудь по-другому, например shift_parameters или как-то так.

2022-05-07 19:09 UTC, DimaTrushin commented on ComputeBlock.cpp
> +    A_shift_ += chain_rule * grad_A();
Если уж ты накапливаешь шифт, то тебе надо еще хранить сколько таких ты накопил, чтобы поделить на их количество в train. И еще этот метод лучше назвать accumulate_shift. Но тогда тебе нужен метод reset_accumulated_shift, чтобы сбросить напопленную сумму градиента для следующего витка обучения.
А так у тебя получилась очень мутная система, особенно учитывая, что названия ничего не говорят о функциях.

2022-05-07 19:09 UTC, DimaTrushin commented on ComputeBlock.cpp
> +    A_ -= step * A_shift_;
Это не train, это apply_accumulted_shift

2022-05-11 19:36 UTC, DimaTrushin requested changes

2022-05-11 19:36 UTC, DimaTrushin commented on CMakeLists.txt
> +add_executable(main main.cpp Sigmoid.cpp ComputeBlock.cpp Net.cpp LossFunction.cpp Tests.h)
Никогда не добавляй .h файлы в executable! Тут должны быть только .cpp файлы. По своей концепции .h файлы должны и могут включаться в другие файлы. Более того, они могут не содержать полных определений объектов (например, не содержать имплементации методов класса), а потому могут банально не компилироваться.

2022-05-11 19:36 UTC, DimaTrushin commented on ComputeBlock.h
> +    Index cols_;
cols_ и rows_ не нужны. Они у тебя известны, потому что известны размеры A_ и b_. Потому их не надо хранить. Это лишние параметры, которые ты можешь забыть обновить.
Сделай методы
```cpp
Index rows() const {
  return A_.rows();
}
Index columns() const {...}
```

2022-05-11 19:36 UTC, DimaTrushin commented on ComputeBlock.h
> +    Vector db_;
Я бы еще предложил хранить Index BatchSize_ как количество элементов которые мы уже напихали внутрь dA_ и db, чтобы потом, когда ты будешь сдвигаться на градиет поделитьб на это количество.

2022-05-11 19:36 UTC, DimaTrushin commented on ComputeBlock.h
> +    Vector input_;
Выглядит так, что это лишнее данное. Я бы сделал метод, который его использует принимающим Input_ на вход. И уже Net будет передавать закэшированное output предыдущего слоя в виде input для текущего слоя.

2022-05-11 19:36 UTC, DimaTrushin commented on LossFunction.h
>          return ((z - y).transpose() * (z - y)).trace() / z.cols();
Если я правильно понимаю, то тут считается
\sum_ij (z_ij - y_ij)^2
Выглядит как что-то, что реализовать бы через array().

2022-05-11 19:36 UTC, DimaTrushin commented on LossFunction.h
> +    Vector grad_z(const Vector &z, const Vector &y) {
А почему нет матричной версии? Которая принимает сразу пачку векторов.

2022-05-11 19:36 UTC, DimaTrushin commented on Net.cpp
> +Net::Net(const std::vector<Index>& layers_sizes, TolerenceType tol, LearningRateType lr)
тут лучше использовать initializer_list
```cpp
Net::Net(std::initializer_list<Index> layer_sizes, ... ) : ... {...}
```
Дело  в том, что когда ты инициализируешь сеть так Net({1, 2, 3}, ...), то у тебя {} создают initializer_list, а потом твой конструктор дополнительно создает из него вектор. Это лишний расход ресурсов.

2022-05-11 19:36 UTC, DimaTrushin commented on Net.cpp
> +        update_parameters(lr_);
С твоей имплементацией, я бы ожидал тут lr_ / x.cols()

2022-05-11 19:36 UTC, DimaTrushin commented on Net.cpp
> +        reset_grad();
Лучше градиент сбрасывать до, а не после. Потому что для выполнения метода тебе важно, чтобы в начале каждой итерации while у тебя dA_ и db_ были нулями, а в конце это не так нужно. Конкретно в твоей имплементации это ничего не изменит. Но вдруг ты до метода train что-нибудь вызовешь, что испортит dA_ и db_. Метод должен либо проверять assert-ами preconditions, либо сам их устанавливать.

2022-05-11 19:36 UTC, DimaTrushin commented on Tests.h
> +}
Привет отсутствие новой строки.

2022-05-11 19:36 UTC, DimaTrushin commented on Tests.h
> +void test_all() {
сделай этот файл .cpp фалом. А в .h файл вынеси только declaration этой функции.

2022-05-11 19:36 UTC, DimaTrushin commented on Tests.h
> +using Vector = Net::Vector;
обернуть в anonymous namespace после переноса в cpp файл.

2022-05-11 19:36 UTC, DimaTrushin commented on Net.cpp
> +        arg = layer.push_forward(arg);
Ты нигде не применяешь sigmoid в слое. У тебя слои линейные!

2022-05-11 19:36 UTC, DimaTrushin commented on ComputeBlock.h
> +        output_ = A_ * x + b_;
Тут скорее всего должно быть evaluate_1d(x); Иначе у тебя слой просто линейный.

2022-05-11 19:36 UTC, DimaTrushin commented on Net.cpp
> +    Matrix arg = loss_.grad_z(z, y);
Вот это ОЧЕНЬ странно. grad_z возвращает Vector, потом ты его преобразуешь к матрице arg, видимо диагональной. А потом ты через каждый слой пропускаешь эту диагональную матрицу. Какого хрена тут происходит?
UPD Это лажа!

2022-05-24 14:11 UTC, DimaTrushin requested changes
Нашел пару багов.

2022-05-24 14:11 UTC, DimaTrushin commented on ComputeBlock.cpp
> +        activation_function_ = new Sigmoid;
А ничего, что у тебя память течет. Так как деструктор не освобождает ее? Тут надо использовать std::unique_ptr и std::make_unique.

2022-05-24 14:11 UTC, DimaTrushin commented on ActivationFunction.h
> +};
nbew line

2022-05-24 14:11 UTC, DimaTrushin commented on ActivationFunction.h
> +    virtual ~ActivationFunction(){};
virtual ~AcitvationFunction() = default;

2022-05-24 14:11 UTC, DimaTrushin commented on ComputeBlock.h
> +    ActivationFunction *activation_function_ = nullptr;
Никогда не используй сырые указатели для владения. Сделай std::unique_ptr.

2022-05-24 14:11 UTC, DimaTrushin commented on Net.cpp
> +Net::Net(const std::vector<Index>& layers_sizes, const std::vector<std::string>& layers_types,
почему vector, а не initializer_list? У тебя же лишний вектор конструируется в таком случае.

2022-05-24 14:11 UTC, DimaTrushin commented on Net.cpp
> +    std::random_device rd;
Лучше сделать статический генератор, чтобы он инициализировался один раз. А то у тебя на каждом вызове этой функции генератор сбрасывается в одно и то же состояние.

2022-05-24 14:11 UTC, DimaTrushin commented on ReadMnist.h
> +int ReverseInt(int i);
эта функция вряд ли нужна тебе в хедере, она же деталь имплементации.

2022-05-24 14:11 UTC, DimaTrushin commented on Relu.h
> +        return 0.01 * x;
Магическая константа для ReLu. Я так понимаю это трюк, чтобы градиент не умирал.

2022-05-24 14:31 UTC, toobrainless commented on Relu.h
> +        return 0.01 * x;
Да, об этом я упомянул в своем отчете

2022-05-24 14:45 UTC, toobrainless commented on ComputeBlock.h
> +    ActivationFunction *activation_function_ = nullptr;
Да ты мне как-то по шапке надавал за умные указатели, вот я от них и отказался

2022-05-27 11:05 UTC, merged